-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Establishment Settings
create table public.establishment_settings (
  id uuid default uuid_generate_v4() primary key,
  name text not null default 'Lido Manager',
  rows integer not null default 6,
  cols integer not null default 10,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default settings
insert into public.establishment_settings (name, rows, cols) values ('Lido Manager', 6, 10);

-- 2. Beach Price Rules (Row Pricing)
create table public.beach_price_rules (
  id uuid default uuid_generate_v4() primary key,
  row_label text not null unique,
  daily_price decimal(10,2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default prices
insert into public.beach_price_rules (row_label, daily_price) values 
  ('A', 30.00), ('B', 25.00), ('C', 20.00), ('D', 15.00), ('E', 15.00), ('F', 10.00);

-- 3. Service Menu Items
create type service_category as enum ('bar', 'restaurant', 'service', 'other');

create table public.service_items (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  category service_category not null,
  price decimal(10,2) not null,
  available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default services
insert into public.service_items (name, category, price) values 
  ('Caffè Espresso', 'bar', 1.50),
  ('Cappuccino', 'bar', 2.00),
  ('Acqua Naturale 0.5L', 'bar', 1.50),
  ('Club Sandwich', 'restaurant', 12.00),
  ('Insalata Mista', 'restaurant', 8.00),
  ('Spritz Aperol', 'bar', 5.00),
  ('Noleggio Kayak (1h)', 'service', 15.00),
  ('Giro in Barca', 'service', 25.00),
  ('Noleggio Pedalò (1h)', 'service', 12.00);

-- 4. Umbrella Spots (The Grid)
create type umbrella_status as enum ('free', 'occupied', 'reserved');

create table public.umbrella_spots (
  id text primary key, -- e.g. "A1", "B2"
  row_label text not null,
  number integer not null,
  status umbrella_status default 'free',
  sunbeds integer default 0 check (sunbeds >= 0 and sunbeds <= 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: Umbrella spots are usually generated by code, but can be persisted here.

-- 5. Transactions
create type payment_method as enum ('cash', 'card');

create table public.transactions (
  id uuid default uuid_generate_v4() primary key,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  total decimal(10,2) not null,
  payment_method payment_method not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Transaction Items
create type item_type as enum ('product', 'umbrella', 'service');

create table public.transaction_items (
  id uuid default uuid_generate_v4() primary key,
  transaction_id uuid references public.transactions(id) on delete cascade not null,
  name text not null,
  price decimal(10,2) not null,
  quantity integer not null default 1,
  type item_type not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) Policies
-- For simplicity in this demo, we enable public access, but in production use authenticated roles.
alter table public.establishment_settings enable row level security;
alter table public.beach_price_rules enable row level security;
alter table public.service_items enable row level security;
alter table public.umbrella_spots enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;

-- Public access policies (Change these for production!)
create policy "Public read access" on public.establishment_settings for select using (true);
create policy "Public read access" on public.beach_price_rules for select using (true);
create policy "Public read access" on public.service_items for select using (true);
create policy "Public read access" on public.umbrella_spots for select using (true);
create policy "Public read access" on public.transactions for select using (true);
create policy "Public read access" on public.transaction_items for select using (true);

create policy "Public insert/update access" on public.establishment_settings for all using (true);
create policy "Public insert/update access" on public.beach_price_rules for all using (true);
create policy "Public insert/update access" on public.service_items for all using (true);
create policy "Public insert/update access" on public.umbrella_spots for all using (true);
create policy "Public insert/update access" on public.transactions for all using (true);
create policy "Public insert/update access" on public.transaction_items for all using (true);
